# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS-inst-clstr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS-inst-clstr
  pod 'SwiftyZeroMQ5', :git => 'https://github.com/appliedengineering/SwiftyZeroMQ5.git', :branch => 'master'
  pod 'Charts'

  target 'IOS-inst-clstrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOS-inst-clstrUITests' do
    # Pods for testing
  end

end
